name: "Web Services Base"
description: "Add base settings for UBC Web Services websites"
type: "Site"
install:
  # core
  - block
  - block_content
  - breakpoint
  - ckeditor5
  - contextual
  - file
  - image
  - jsonapi
  - media
  - media_library
  - menu_ui
  - path
  - responsive_image
  - rest
  - taxonomy
  - toolbar
  - user
  # contrib
  - admin_toolbar
  - admin_toolbar_tools
  - antibot
  - block_exclude_pages
  - chosen
  - ckeditor5_fullscreen
  - config_ignore
  - crop
  - date_popup
  - dropzonejs
  - editor_advanced_link
  - easy_breadcrumb
  - file_delete
  - file_to_media
  - focal_point
  - formtips
  - fullcalendar_view
  - gin
  - gin_login
  - gin_toolbar
  - google_analytics
  - image_widget_crop
  - kraken
  - linkit
  - linkit_media_library
  - media_bulk_upload_dropzonejs
  - media_alias_display
  - media_bulk_upload
  - media_entity_file_replace
  - menu_block
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - node_revision_delete
  - optional_end_date
  - pathauto
  - quick_node_clone
  - rebuild_cache_access
  - redirect
  - responsive_table_filter
  - role_delegation
  - scheduler
  - smtp
  - svg_image
  - twig_tweak
  - ubc_chosen_style_tweaks
  - ubc_ckeditor_widgets
  - ubc_media_entities
  - view_unpublished
  - views_autosubmit
  - webform
  - webform_node
  - webform_ui
config:
  import:
    ckeditor5:
      - editor.editor.filtered_text.yml
      - filter.format.filtered_text.yml
      - editor.editor.simple.yml
      - filter.format.simple.yml
    config_ignore: "*"
    dropzonejs: "*"
    editor_advanced_link: "*"
    focal_point: "*"
    fullcalendar_view: "*"
    google_analytics: "*"
    image_widget_crop: "*"
    kraken: "*"
    linkit: "*"
    metatag: "*"
    redirect: "*"
    responsive_table_filter: "*"
    scheduler: "*"
    simple_sitemap: "*"
    ubc_ckeditor_widgets: "*"
    webform: "*"
    webform_node: "*"
  actions:
    # THEME set themes
    system.theme:
      simple_config_update:
        admin: gin
        default: kraken
    # GIN configure blocks
    block.block.gin_help:
      simple_config_update:
        region: help
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
    block.block.gin_secondary_local_tasks:
      simple_config_update:
        region: pre_content
    block.block.gin_primary_admin_actions:
      simple_config_update:
        region: content
    # GIN disable unneeded blocks
    block.block.gin_search_form_wide:
      simple_config_update:
        status: false
    block.block.gin_search_form_narrow:
      simple_config_update:
        status: false
    block.block.gin_account_menu:
      simple_config_update:
        status: false
    block.block.gin_main_menu:
      simple_config_update:
        status: false
    block.block.gin_powered:
      simple_config_update:
        status: false
    block.block.gin_syndicate:
      simple_config_update:
        status: false
    block.block.gin_site_branding:
      simple_config_update:
        status: false
    # KRAKEN configure blocks
    block.block.kraken_help:
      simple_config_update:
        region: help
    block.block.kraken_messages:
      simple_config_update:
        region: help
    # KRAKEN disable unneeded blocks
    block.block.kraken_page_title:
      simple_config_update:
        status: false
    block.block.kraken_powered:
      simple_config_update:
        status: false
    block.block.kraken_search_form_wide:
      simple_config_update:
        status: false
    block.block.kraken_search_form_narrow:
      simple_config_update:
        status: false
    block.block.kraken_account_menu:
      simple_config_update:
        status: false
    block.block.kraken_syndicate:
      simple_config_update:
        status: false
    block.block.kraken_site_branding:
      simple_config_update:
        status: false
    block.block.kraken_content:
      simple_config_update:
        status: false
    block.block.kraken_primary_admin_actions:
      simple_config_update:
        status: false
    block.block.kraken_primary_local_tasks:
      simple_config_update:
        status: false
    # MEDIA enable standalone media settings
    media.settings:
      simple_config_update:
        standalone_url: 1
    # RESPONSIVE IMAGE wide image style
    responsive_image.styles.wide:
      ensure_exists:
        langcode: en
        status: true
        dependencies:
          config:
            - image.style.max_1300x1300
            - image.style.max_2600x2600
            - image.style.max_970x970
            - image.style.max_650x650
            - image.style.max_325x325
        id: wide
        label: Wide
        image_style_mappings:
          -
            image_mapping_type: image_style
            image_mapping: max_650x650
            breakpoint_id: kraken.micro
            multiplier: 1x
          -
            image_mapping_type: image_style
            image_mapping: max_970x970
            breakpoint_id: kraken.sm
            multiplier: 1x
          -
            image_mapping_type: image_style
            image_mapping: max_1300x1300
            breakpoint_id: kraken.md
            multiplier: 1x
          -
            image_mapping_type: image_style
            image_mapping: max_2600x2600
            breakpoint_id: kraken.lg
            multiplier: 1x
          -
            image_mapping_type: image_style
            image_mapping: max_2600x2600
            breakpoint_id: kraken.xl
            multiplier: 1x
          -
            image_mapping_type: image_style
            image_mapping: max_2600x2600
            breakpoint_id: kraken.xxl
            multiplier: 1x
        breakpoint_group: kraken
        fallback_image_style: max_325x325
    # RESPONSIVE IMAGE narrow image style
    responsive_image.styles.narrow:
      ensure_exists:
        langcode: en
        status: true
        dependencies:
          config:
            - image.style.max_1300x1300
            - image.style.max_2600x2600
            - image.style.max_970x970
        id: narrow
        label: Narrow
        image_style_mappings:
          -
            image_mapping_type: image_style
            image_mapping: max_325x325
            breakpoint_id: kraken.micro
            multiplier: 1x
          -
            image_mapping_type: image_style
            image_mapping: max_325x325
            breakpoint_id: kraken.sm
            multiplier: 1x
          -
            image_mapping_type: image_style
            image_mapping: max_650x650
            breakpoint_id: kraken.md
            multiplier: 1x
          -
            image_mapping_type: image_style
            image_mapping: max_970x970
            breakpoint_id: kraken.lg
            multiplier: 1x
          -
            image_mapping_type: image_style
            image_mapping: max_970x970
            breakpoint_id: kraken.xl
            multiplier: 1x
          -
            image_mapping_type: image_style
            image_mapping: max_1300x1300
            breakpoint_id: kraken.xxl
            multiplier: 1x
        breakpoint_group: kraken
        fallback_image_style: max_325x325
    # ROLE assign permissions
    user.role.anonymous:
      grantPermissions:
        - 'view media'
    # ROLE add editor role and assign permissions
    user.role.editor:
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'access administration pages'
        - 'access block library'
        - 'access content overview'
        - 'access contextual links'
        - 'access files overview'
        - 'access media overview'
        - 'access site in maintenance mode'
        - 'access taxonomy overview'
        - 'access toolbar'
        - 'access user profiles'
        - 'administer blocks'
        - 'administer menu'
        - 'administer nodes'
        - 'administer themes'
        - 'administer url aliases'
        - 'administer users'
        - 'cancel account'
        - 'change own username'
        - 'create url aliases'
        - 'delete any file'
        - 'delete any media'
        - 'delete media'
        - 'dropzone upload files'
        - 'select account cancellation method'
        - 'update any media'
        - 'update media'
        - 'use bulk_upload_documents bulk upload form'
        - 'use bulk_upload_images bulk upload form'
        - 'use text format filtered_text'
        - 'view all media revisions'
        - 'view media'
        - 'view own unpublished media'
        - 'view the administration theme'
        - 'create audio media'
        - 'delete any audio media'
        - 'delete own audio media'
        - 'edit any audio media'
        - 'edit own audio media'
        - 'view any audio media revisions'
        - 'delete any audio media revisions'
        - 'revert any audio media revisions'
        - 'create file media'
        - 'delete any file media'
        - 'delete own file media'
        - 'edit any file media'
        - 'edit own file media'
        - 'view any file media revisions'
        - 'delete any file media revisions'
        - 'revert any file media revisions'
        - 'create ics_file media'
        - 'delete any ics_file media'
        - 'delete own ics_file media'
        - 'edit any ics_file media'
        - 'edit own ics_file media'
        - 'view any ics_file media revisions'
        - 'delete any ics_file media revisions'
        - 'revert any ics_file media revisions'
        - 'create image media'
        - 'delete any image media'
        - 'delete own image media'
        - 'edit any image media'
        - 'edit own image media'
        - 'view any image media revisions'
        - 'delete any image media revisions'
        - 'revert any image media revisions'
        - 'create private_file media'
        - 'delete any private_file media'
        - 'delete own private_file media'
        - 'edit any private_file media'
        - 'edit own private_file media'
        - 'view any private_file media revisions'
        - 'delete any private_file media revisions'
        - 'revert any private_file media revisions'
        - 'create remote_video media'
        - 'delete any remote_video media'
        - 'delete own remote_video media'
        - 'edit any remote_video media'
        - 'edit own remote_video media'
        - 'view any remote_video media revisions'
        - 'delete any remote_video media revisions'
        - 'revert any remote_video media revisions'
        - 'create svg_icon media'
        - 'delete any svg_icon media'
        - 'delete own svg_icon media'
        - 'edit any svg_icon media'
        - 'edit own svg_icon media'
        - 'view any svg_icon media revisions'
        - 'delete any svg_icon media revisions'
        - 'revert any svg_icon media revisions'
    # ROLE add content_creator role and assign permissions
    user.role.content_creator:
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'access administration pages'
        - 'access content overview'
        - 'access files overview'
        - 'access media overview'
        - 'access site in maintenance mode'
        - 'access taxonomy overview'
        - 'access toolbar'
        - 'administer menu'
        - 'administer url aliases'
        - 'create url aliases'
        - 'delete any media'
        - 'delete media'
        - 'dropzone upload files'
        - 'update any media'
        - 'update media'
        - 'use bulk_upload_documents bulk upload form'
        - 'use bulk_upload_images bulk upload form'
        - 'use text format filtered_text'
        - 'view all media revisions'
        - 'view media'
        - 'view own unpublished media'
        - 'view the administration theme'
        - 'create file media'
        - 'delete any file media'
        - 'delete own file media'
        - 'edit any file media'
        - 'edit own file media'
        - 'view any file media revisions'
        - 'delete any file media revisions'
        - 'revert any file media revisions'
        - 'create ics_file media'
        - 'delete any ics_file media'
        - 'delete own ics_file media'
        - 'edit any ics_file media'
        - 'edit own ics_file media'
        - 'view any ics_file media revisions'
        - 'delete any ics_file media revisions'
        - 'revert any ics_file media revisions'
        - 'create image media'
        - 'delete any image media'
        - 'delete own image media'
        - 'edit any image media'
        - 'edit own image media'
        - 'view any image media revisions'
        - 'delete any image media revisions'
        - 'revert any image media revisions'
        - 'create private_file media'
        - 'delete any private_file media'
        - 'delete own private_file media'
        - 'edit any private_file media'
        - 'edit own private_file media'
        - 'view any private_file media revisions'
        - 'delete any private_file media revisions'
        - 'revert any private_file media revisions'
        - 'create remote_video media'
        - 'delete any remote_video media'
        - 'delete own remote_video media'
        - 'edit any remote_video media'
        - 'edit own remote_video media'
        - 'view any remote_video media revisions'
        - 'delete any remote_video media revisions'
        - 'revert any remote_video media revisions'
        - 'create svg_icon media'
        - 'delete any svg_icon media'
        - 'delete own svg_icon media'
        - 'edit any svg_icon media'
        - 'edit own svg_icon media'
        - 'view any svg_icon media revisions'
        - 'delete any svg_icon media revisions'
        - 'revert any svg_icon media revisions'
    # ROLE admin role weight
    user.role.administrator:
      simple_config_update:
        weight: 10
    # ANTIBOT settings
    antibot.settings:
      simple_config_update:
        form_ids:
          - 'comment_*'
          - user_login_form
          - user_pass
          - user_register_form
          - 'contact_message_*'
          - 'webform_*'
    # CHOSEN settings
    chosen.settings:
      simple_config_update:
        minimum_single: '0'
        minimum_multiple: '0'
        max_shown_results: '20'
        minimum_width: '100'
        use_relative_width: 'true'
        search_contains: 'true'
        chosen_include: '0'
    # METATAG settings
    metatag.metatag_defaults.global:
      simple_config_update:
        tags.canonical_url: '[current-page:url]'
        tags.title: '[current-page:title] | [site:name]'
    metatag.metatag_defaults.front:
      simple_config_update:
        tags.canonical_url: '[node:url]'
        tags.description: '[node:summary]'
        tags.title: '[node:title] | [site:name]'
    metatag.metatag_defaults.node:
      simple_config_update:
        tags.canonical_url: '[node:url]'
        tags.description: '[node:summary]'
        tags.title: '[node:title] | [site:name]'
        tags.og_description: '[node:summary]'
        tags.og_site_name: '[site:name]'
        tags.og_title: '[node:title]'
        tags.og_url: '[node:url]'
        tags.twitter_cards_description: '[node:summary]'
        tags.twitter_cards_page_url: '[node:url]'
        tags.twitter_cards_title: '[node:title]'
        tags.twitter_cards_type: 'summary'
    # MEDIA - REMOTE VIDEO alter default view mode
    core.entity_view_display.media.remote_video.default:
      setComponents:
        -
          name: field_media_oembed_video
          options:
            type: oembed
            label: hidden
            settings:
              max_width: 900
              max_height: 506
              loading:
                attribute: lazy
            third_party_settings: {  }
            weight: 0
            region: content
        -
          name: thumbnail
          options:
            type: image
            label: hidden
            settings:
              image_link: ''
              image_style: video_thumbnail
              image_loading:
                attribute: lazy
            third_party_settings: {  }
            weight: 0
            region: content
    # MEDIA - SVG add icon_large image style
    image.style.icon_large:
      createIfNotExists:
        langcode: en
        status: true
        dependencies: {  }
        name: icon_large
        label: 'Icon, large'
        effects:
          f9973a7b-6e05-4c2a-983b-ad1c5816b4e0:
            uuid: f9973a7b-6e05-4c2a-983b-ad1c5816b4e0
            id: image_scale_and_crop
            weight: 1
            data:
              width: 96
              height: 96
              anchor: center-center
    # MEDIA - SVG addd icon_small image style
    image.style.icon_small:
      createIfNotExists:
        langcode: en
        status: true
        dependencies: {  }
        name: icon_small
        label: 'Icon, small'
        effects:
          aed7f070-e2f5-44a1-965c-4d1564f3bc2b:
            uuid: aed7f070-e2f5-44a1-965c-4d1564f3bc2b
            id: image_scale_and_crop
            weight: 1
            data:
              width: 24
              height: 24
              anchor: center-center
    # MEDIA - SVG alter icon_small view mode
    core.entity_view_mode.media.small_icon:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - media
        id: media.small_icon
        label: 'Small icon'
        targetEntityType: media
        cache: true
    # NODE_REVISION_DELETE settings
    node_revision_delete.settings:
      simple_config_update:
        node_revision_delete_time: '0'
        delete_newer: 'false'
    # SCHEDULER settings
    scheduler.settings:
      simple_config_update:
        allow_date_only: 1
        default_time: '00:00'
        hide_seconds: 1
    # SMTP settings
    smtp.settings:
      simple_config_update:
        smtp_on: 1
        smtp_host: 'smtp.mail.ubc.ca'
        smtp_port: 587
        smtp_protocol: 'tls'
        smtp_autotls: 1
        smtp_username: 'ubcuit-a-UBCITWSNR'
        smtp_client_helo: 'mail.ubc.ca'
